CinemaPro.WebUI/Areas/Admin/Controllers/McastsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CinemaPro.Domain.DataContext;
using CinemaPro.Domain.Entity;

namespace CinemaPro.WebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class McastsController : Controller
    {
        private readonly CinemaDbContext _context;

        public McastsController(CinemaDbContext context)
        {
            _context = context;
        }

        // GET: Admin/Mcasts
        public async Task<IActionResult> Index()
        {
            var cinemaDbContext = _context.Mcasts.Include(m => m.Cast).Include(m => m.Moviedetail);
            return View(await cinemaDbContext.ToListAsync());
        }

        // GET: Admin/Mcasts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mcast = await _context.Mcasts
                .Include(m => m.Cast)
                .Include(m => m.Moviedetail)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (mcast == null)
            {
                return NotFound();
            }

            return View(mcast);
        }

        // GET: Admin/Mcasts/Create
        public IActionResult Create()
        {
            ViewData["CastId"] = new SelectList(_context.Casts, "Id", "Fullname");
            ViewData["MoviedetailId"] = new SelectList(_context.Moviedetails, "Id", "Name");
            return View();
        }

        // POST: Admin/Mcasts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,MoviedetailId,CastId")] Mcast mcast)
        {
            if (ModelState.IsValid)
            {
                _context.Add(mcast);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CastId"] = new SelectList(_context.Casts, "Id", "Fullname", mcast.CastId);
            ViewData["MoviedetailId"] = new SelectList(_context.Moviedetails, "Id", "Name", mcast.MoviedetailId);
            return View(mcast);
        }

        // GET: Admin/Mcasts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mcast = await _context.Mcasts.FindAsync(id);
            if (mcast == null)
            {
                return NotFound();
            }
            ViewData["CastId"] = new SelectList(_context.Casts, "Id", "Fullname", mcast.CastId);
            ViewData["MoviedetailId"] = new SelectList(_context.Moviedetails, "Id", "Name", mcast.MoviedetailId);
            return View(mcast);
        }

        // POST: Admin/Mcasts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,MoviedetailId,CastId")] Mcast mcast)
        {
            if (id != mcast.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(mcast);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!McastExists(mcast.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CastId"] = new SelectList(_context.Casts, "Id", "Fullname", mcast.CastId);
            ViewData["MoviedetailId"] = new SelectList(_context.Moviedetails, "Id", "Name", mcast.MoviedetailId);
            return View(mcast);
        }

        // GET: Admin/Mcasts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mcast = await _context.Mcasts
                .Include(m => m.Cast)
                .Include(m => m.Moviedetail)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (mcast == null)
            {
                return NotFound();
            }

            return View(mcast);
        }

        // POST: Admin/Mcasts/Delete/5
        [HttpPost, ActionName("Delete")]
      //  [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var mcast = await _context.Mcasts.FindAsync(id);
            _context.Mcasts.Remove(mcast);
            await _context.SaveChangesAsync();
 
            return Json(new
            {
                error = false,
                message = "ok"
            });
            // return RedirectToAction(nameof(Index));
        }

        private bool McastExists(int id)
        {
            return _context.Mcasts.Any(e => e.Id == id);
        }
    }
}

CinemaPro.WebUI/Areas/Admin/Controllers/McatsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CinemaPro.Domain.DataContext;
using CinemaPro.Domain.Entity;

namespace CinemaPro.WebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class McatsController : Controller
    {
        private readonly CinemaDbContext _context;

        public McatsController(CinemaDbContext context)
        {
            _context = context;
        }

        // GET: Admin/Mcats
        public async Task<IActionResult> Index()
        {
            var cinemaDbContext = _context.Mcats.Include(m => m.Category).Include(m => m.Moviedetail);
            return View(await cinemaDbContext.ToListAsync());
        }

        // GET: Admin/Mcats/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mcat = await _context.Mcats
                .Include(m => m.Category)
                .Include(m => m.Moviedetail)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (mcat == null)
            {
                return NotFound();
            }

            return View(mcat);
        }

        // GET: Admin/Mcats/Create
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name");
            ViewData["MoviedetailId"] = new SelectList(_context.Moviedetails, "Id", "Name");
            return View();
        }

        // POST: Admin/Mcats/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CategoryId,MoviedetailId")] Mcat mcat)
        {
            if (ModelState.IsValid)
            {
                _context.Add(mcat);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", mcat.CategoryId);
            ViewData["MoviedetailId"] = new SelectList(_context.Moviedetails, "Id", "Name", mcat.MoviedetailId);
            return View(mcat);
        }

        // GET: Admin/Mcats/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mcat = await _context.Mcats.FindAsync(id);
            if (mcat == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", mcat.CategoryId);
            ViewData["MoviedetailId"] = new SelectList(_context.Moviedetails, "Id", "Name", mcat.MoviedetailId);
            return View(mcat);
        }

        // POST: Admin/Mcats/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CategoryId,MoviedetailId")] Mcat mcat)
        {
            if (id != mcat.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(mcat);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!McatExists(mcat.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", mcat.CategoryId);
            ViewData["MoviedetailId"] = new SelectList(_context.Moviedetails, "Id", "Name", mcat.MoviedetailId);
            return View(mcat);
        }

        // GET: Admin/Mcats/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mcat = await _context.Mcats
                .Include(m => m.Category)
                .Include(m => m.Moviedetail)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (mcat == null)
            {
                return NotFound();
            }

            return View(mcat);
        }

        // POST: Admin/Mcats/Delete/5
        [HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var mcat = await _context.Mcats.FindAsync(id);
            _context.Mcats.Remove(mcat);
            await _context.SaveChangesAsync();
           
            return Json(new
            {
                error = false,
                message = "ok"
            });
          //  return RedirectToAction(nameof(Index));
        }

        private bool McatExists(int id)
        {
            return _context.Mcats.Any(e => e.Id == id);
        }
    }
}

CinemaPro.WebUI/Areas/Admin/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <link rel="icon" type="image/png" href="assets/img/favicon.ico">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <title>CinemaPro Admin</title>

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />
    <link href="~/Admin/assets/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Admin/assets/css/animate.min.css" rel="stylesheet" />
    <link href="~/Admin/assets/css/light-bootstrap-dashboard.css?v=1.4.0" rel="stylesheet" />
    <link href="~/Admin/assets/css/demo.css" rel="stylesheet" />
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
    <link href="~/Admin/assets/css/pe-icon-7-stroke.css" rel="stylesheet" />
    <link rel="shortcut icon" type="image/png" href="~/assets/images/header/favicon.ico" />
    <style>
        .operate-cell {
            text-align: right;
            min-width: 240px;
        }

        .img-size {
            width: 70px;
        }

        #myInput {
            font-size: 14px;
            line-height: 29px;
            width: 100%;
            max-width: 400px;
            font-weight: 300;
            color: #777777;
            padding-left: 20px;
            border-radius: 45px;
            z-index: 0;
            margin-bottom: 22px;
            border: double 2px transparent;
            background-image: linear-gradient(white, white), radial-gradient(circle at top left, #4458dc, #854fee);
            background-origin: border-box;
            background-clip: content-box, border-box;
            padding: 0;
            text-indent: 20px;
        }
    </style>

    @RenderSection("css", required: false)
</head>
<body>

    <div class="wrapper">
        <div class="sidebar" data-color="purple" data-image="assets/img/sidebar-5.jpg">

          


            <div class="sidebar-wrapper">
                <div class="logo">
                    <a href="#" class="simple-text">
                        CinemaProPanel
                    </a>
                </div>

                <ul class="nav">
                    @*<li>
            <a href="dashboard.html">
                <i class="pe-7s-graph"></i>
                <p>Dashboard</p>
            </a>
        </li>*@
                    <li>
                        <a asp-controller="moviedetails" asp-action="index">
                            <i class="fas fa-film"></i>
                            <p>Movie</p>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="directors" asp-action="index">
                            <i class="pe-7s-user"></i>

                            <p>Director</p>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="languages" asp-action="index">
                            <i class="fas fa-language"></i>
                            <p>Language</p>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="bthes" asp-action="index">
                            <i class="fas fa-file-video"></i>
                            <p>BtheS</p>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="formats" asp-action="index">
                            <i class="pe-7s-note2"></i>
                            <p>Format</p>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="Mformats" asp-action="index">
                            <i class="pe-7s-note2"></i>
                            <p>MovieFormat</p>
                        </a>
                    </li>

                    <li>
                        <a asp-controller="Categories" asp-action="index">
                            <i class="fas fa-list"></i>
                            <p>Category</p>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="Mcats" asp-action="index">
                            <i class="fas fa-list"></i>
                            <p>MCategory</p>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="casts" asp-action="index">
                            <i class="pe-7s-user"></i>
                            <p>Cast</p>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="Mcasts" asp-action="index">
                            <i class="pe-7s-user"></i>
                            <p>MCast</p>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="socialmedias" asp-action="index">
                            <i class="fas fa-hashtag"></i>
                            <p>SocialMedia</p>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="partners" asp-action="index">
                            <i class="far fa-handshake"></i>
                            <p>Partner</p>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="tickets" asp-action="index">
                            <i class="fas fa-ticket-alt"></i>
                            <p>Ticket</p>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="extras" asp-action="index">
                            <i class="fas fa-hamburger"></i>
                            <p>Extra</p>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="seats" asp-action="index">
                            <i class="fas fa-chair"></i>
                            <p>Seat</p>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="contacts" asp-action="index">
                            <i class="far fa-address-card"></i>
                            <p>Contacts</p>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="contactus" asp-action="index">
                            <i class="fas fa-file-signature"></i>
                            <p>Message</p>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="Account" asp-action="ChangePassword">
                            <i class="fas fa-key"></i>
                            <p>Change Password</p>
                        </a>
                    </li>
                </ul>
            </div>
        </div>

        <div class="main-panel">
            <nav class="navbar navbar-default navbar-fixed">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="collapse navbar-collapse">
                   

                        <ul class="nav navbar-nav navbar-right">
                         
                           
                            <form method="post" asp-controller="account" asp-action="logout">
                                <button type="submit" class="nav-link btn btn-link text-dark">
                                    <p>Log out</p>
                                </button>
                            </form>
                            <li class="separator hidden-lg hidden-md"></li>
                        </ul>
                    </div>
                </div>
            </nav>


            @RenderBody()

           


        </div>
    </div>


    <script src="~/Admin/assets/js/jquery.3.2.1.min.js" type="text/javascript"></script>
    <script src="~/Admin/assets/js/bootstrap.min.js" type="text/javascript"></script>

  
    <script src="~/Admin/assets/js/chartist.min.js"></script>

  
    <script src="~/Admin/assets/js/bootstrap-notify.js"></script>

 
    <script src="https://kit.fontawesome.com/65af04a3f4.js" crossorigin="anonymous"></script>

    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>


    <script src="~/Admin/assets/js/light-bootstrap-dashboard.js?v=1.4.0"></script>

  
    <script src="~/Admin/assets/js/demo.js"></script>
    <script>
        $(`[href='${window.location.pathname}']`).closest('li').addClass('active');
    </script>

    @RenderSection("scripts", required: false)
</body>



</html>